/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stratosdb_sql_extension_NativeExtensionBridge */

#ifndef _Included_com_stratosdb_sql_extension_NativeExtensionBridge
#define _Included_com_stratosdb_sql_extension_NativeExtensionBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stratosdb_sql_extension_NativeExtensionBridge
 * Method:    dlopenLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_stratosdb_sql_extension_NativeExtensionBridge_dlopenLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_stratosdb_sql_extension_NativeExtensionBridge
 * Method:    dlsymFunction
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_stratosdb_sql_extension_NativeExtensionBridge_dlsymFunction
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_stratosdb_sql_extension_NativeExtensionBridge
 * Method:    invokeIntFunction
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_stratosdb_sql_extension_NativeExtensionBridge_invokeIntFunction
  (JNIEnv *, jclass, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
